twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        app_version: '%env(APP_VERSION)%'
        allow_robots: '%env(bool:ALLOW_ROBOTS)%'

when@test:
    twig:
        strict_variables: true
