twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        menu:
            - {label: 'home', route: 'website_home'}
            - {label: 'our courses', route: 'website_courses'}
            - {label: 'the team', route: 'website_team'}
            - {label: 'our achievements', route: 'website_activities'}
            - {label: 'our partners', route: 'website_partners'}
            - {label: 'blog', route: 'website_blog'}
            - {label: 'contact', route: 'website_contact'}
        version:
            3.0
        locales:
            - fr
            - en
        courses:
            - {name: 'symfony2', icon: 'symfony', title: 'Symfony2'}
            - {name: 'oop-uml-scm', icon: 'git', title: 'OOP - UML - SCM'}
            - {name: 'html5-css3', icon: 'html5', title: 'HTML5 - CSS3'}
            - {name: 'wordpress', icon: 'wordpress', title: 'Wordpress'}
        tools:
            - {label: 'symfony', url: 'http://symfony.com', title: 'Symfony'}
            - {label: 'nodejs', url: 'https://nodejs.org', title: 'Node Js'}
            - {label: 'mysql', url: 'https://www.mysql.fr/', title: 'MySQL'}
            - {label: 'mongodb', url: 'https://www.mongodb.org/', title: 'MongoDB'}
            - {label: 'postgresql', url: 'http://www.postgresql.org/', title: 'PostgreSQL'}
            - {label: 'redis', url: 'http://redis.io/', title: 'Redis'}
            - {label: 'varnish', url: 'https://www.varnish-cache.org/', title: 'Varnish'}
            - {label: 'ansible', url: 'http://www.ansible.com/home', title: 'Ansible'}
            - {label: 'elasticsearch', url: 'https://www.elastic.co/fr/products/elasticsearch', title: 'ElasticSearch'}
            - {label: 'docker', url: 'https://www.docker.com/', title: 'Docker'}
            - {label: 'rabbitmq', url: 'https://www.rabbitmq.com/', title: 'RabbitMQ'}
            - {label: 'html5', url: 'https://www.w3.org/TR/html/', title: 'HTML5'}
            - {label: 'css3', url: 'https://www.w3.org/TR/css/', title: 'CSS3'}
            - {label: 'sass', url: 'http://sass-lang.com/', title: 'Sass'}
            - {label: 'vuejs', url: 'https://vuejs.org/', title: 'Vue Js'}
          #  - {label: 'nginx', url: 'https://www.nginx.com/', title: 'Nginx'}
            - {label: 'gitlab', url: 'https://about.gitlab.com/', title: 'GitLab'}
            - {label: 'redmine', url: 'http://www.redmine.org/projects/redmine/wiki', title: 'Redmine'}
            - {label: 'reactjs', url: 'https://reactjs.org/', title: 'React Js'}
            - {label: 'unix_ubuntu', url: 'https://www.ubuntu.com/', title: 'Ubuntu'}
            - {label: 'prestashop', url: 'https://www.prestashop.com/fr', title: 'Prestashop'}
        idci_code_writer:
            files:
                -
                    url: https://raw.githubusercontent.com/IDCI-Consulting/GenealogyBundle/master/Controller/ImageController.php
                    language: 'php'
                    theme: ambiance

                -
                    url: https://raw.githubusercontent.com/IDCI-Consulting/GenealogyBundle/master/Repository/ElementRepository.php
                    language: 'php'
                    theme: monokai

                -
                    url: https://raw.githubusercontent.com/IDCI-Consulting/ExtraFormBundle/master/Controller/ApiController.php
                    language: 'php'
                    theme: tomorrow_night

                -
                    url: https://raw.githubusercontent.com/IDCI-Consulting/SimpleScheduleBundle/master/Entity/LocationAwareCalendarEntity.php
                    language: 'php'
                    theme: chaos

                -
                    url: https://raw.githubusercontent.com/IDCI-Consulting/SimpleScheduleBundle/master/Entity/CalendarEntityRelation.php
                    language: 'php'
                    theme: twilight

                -
                    url: https://raw.githubusercontent.com/IDCI-Consulting/SimpleMetadataBundle/master/Resources/views/Form/fields.html.twig
                    language: 'twig'
                    theme: cobalt

                -
                    url: https://raw.githubusercontent.com/IDCI-Consulting/BrowserCapabilities/master/js/codebarReader.js
                    language: 'javascript'
                    theme: clouds_midnight
        achievements:
            chine_france:
                image_path: "/images/chine-france.png"
                url: "http://www.chine-france.com/"
                title: "Chine France"
                enabled: true
                content:
                    fr: >
                        La Fédération des associations franco-chinoises a pour objectif de regrouper sur une seule et même structure une vingtaine d'associations qui contribuent à renforcer l'amitié entre la France et la Chine.
                        La F.A.F.C propose à ses utilisateurs une base de données contenant des informations, des liens vers les associations et de la documentation culturelle.
                        Le site web est disponible en anglais, français, et chinois.
                    en: >
                        The Federation of French Chinese Associations's objective is to regroup about twenty associations together in a single strucure, which contribute to reinforcing the friendship between China and France.
                        The Federation provides its users with a database containing a lot of information, links to the associations and cultural documentation.
                        This website is available in French, English and Chinese.
                tools: ["wordpress", "html5-css3"]
                services: ["development"]

            le_moniteur:
                image_path: "/images/moniteur.png"
                url: "http://lemoniteur.fr/"
                title: "Le moniteur"
                enabled: true
                content:
                    fr: >
                        lemoniteur.fr est un site d'actualités à destination des acteurs publics et privés de la construction et des collectivités locales.

                        Nous sommes intervenu auprès d'eux pour un audit détaillé de l'ancienne version du site web.
                        Puis, nous avons développé, accompagné les équipes sur le projet de la nouvelle version (mise en ligne en mai 2011)
                        et participé à la refonte du processus de création de compte (inscription) et de l'espace réservé (service Premium).
                    en: >
                        lemoniteur.fr is a news website destined to private and public players from contruction and local communities.

                        We carried out a detailed audit of the old website version. Then we developed, coached teams about the new website version (put up in may 2011)
                        and participated in the reworking of the account creation process (registration) and the restricted area (Premium service).
                tools: ["wordpress"]
                services: ["development", "consulting"]


            www2012:
                image_path: "/images/www2012.png"
                url: "https://www2012.org"
                title: "www2012.org"
                enabled: true
                content:
                    fr: >
                        Le site web www2012 a été développé à l'occasion de la 21e Conférence Internationale World Wide Web,
                        il rassemble les programmes, les partenaires et des documents concernant la conférence.

                        Nous sommes devenus partenaire du consortium World Wide Web 2012 en conceptualisant et en implémentant
                        la partie agenda interactive de la plate-forme du congrès qui a eu lieu en Avril 2012.
                    en: >
                        The www2012 website has been developed on the occasion of the 21st International World Wide Web Conference.
                        It contains the programs, partners and documents in relation with the conference.

                        We have become partner of the World Wide Web 2012 consortium by conceptualizing and implementing the interactive agenda of the congress platform,
                        which took place at April 2012.
                tools: ["wordpress", "html5-css3"]
                services: ["development"]

            carglass:
                image_path: "/images/carglass.png"
                url: "https://www.carglass.fr/"
                title: "Carglass"
                enabled: true
                content:
                    fr: >
                        Carglass, présent dans 34 pays du monde, est expert en réparation et remplacement de vitrage automobile.

                        Nous avons travaillé sur la refonte de leur site web pour améliorer le processus de prise de rendez-vous d'un client lors d'un bris de glace.
                    en: >
                        Carglass is a vehicle glass repair and replacement group operating worldwide across 34 countries.

                        We worked on the redesign of their website to improve customer appointment booking after a glass breakage.
                tools: ["symfony2", "ansible"]
                services: ["development", "consulting"]

            allopneus:
                image_path: "/images/allopneus.png"
                url: "http://www.allopneus.com/"
                title: "Allopneus"
                enabled: true
                content:
                    fr: >
                        Allopneus est un spécialiste et leader français de la vente de pneus sur internet.

                        Nous avons contribué au projet en faisant de la formation et du consulting.
                    en: >
                        Allopneus is a french specialist and leader of online sales of tyres.

                        We contributed to the project by doing training and consulting.
                tools: ["wordpress", "html5-css3"]
                services: ["consulting", "training"]

            optedif:
                image_path: "/images/optedif.png"
                url: "https://optedif-formation.fr/"
                title: "Optedif"
                enabled: true
                content:
                    fr: >
                        Optedif est un site basé sur la mise en relation de formateurs et d'apprenants.
                        Le site web propose des formations dans de nombreux domaines et un espace personnel optimisé en fonction de votre profil.

                        Nous avons participé à l'ajout de nouvelles fonctionnalités, l'amélioration du code source et la créations d'APIs.
                    en: >
                        Optedif is a website aiming to bringing teachers and learners together.
                        The platform provides trainings in plenty of fields and an optimized personnal space adapted to your profile.

                        We took part in source code improvements, API creation and implementation of new functionnalities.
                tools: ["symfony2", "html5-css3", "docker", "rabbitmq"]
                services: ["development"]

            mapyourstories:
                image_path: "/images/mapyourstories.png"
                url: "https://mapyourstories.com/"
                title: "Map Your Stories"
                enabled: true
                content:
                    fr: >
                        Mapyourstories est un site web qui permet de créer des cartes de métro personnalisables et en temps réel.
                        Chaque carte personnalisée peut être imprimé sur un support (tee-shirt, tote bag, etc) et offerte comme cadeau souvenir.

                        Nous avons relevé le challenge en prenant en main le framework MétéorJS et en créant l'éditeur permettant de personnaliser sa map.
                    en: >
                        Mapyourstories is a website allowing users to create cutomizable underground maps which are editable in real time.
                        Each map can be printed out on a tee-shirt, tote bag, etc, and offered as a gift.

                        We have risen up to the challenge by taking the MeteorJS framework in charge and creating the editor allowing one to customize a map.
                tools: ["meteor", "html5-css3"]
                services: ["development"]