image: docker:git
services:
  - docker:dind

variables:
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY/idci/website/php-fpm:$CI_COMMIT_TAG

build-docker-image:
  stage: build
  script:
    - docker login -u $DOCKER_REGISTRY_LOGIN -p $DOCKER_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CONTAINER_RELEASE_IMAGE $CI_PROJECT_DIR -f .docker/php/Dockerfile
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - tags

deploy-to-pre-production:
  stage: deploy
  variables:
    APP_HOST: pre-prod.idci-consulting.fr
    APP_VERSION: $CI_COMMIT_TAG
    SERVICE_NAME: idci_website_pp
  image: docker:latest
  script:
    - docker login -u $DOCKER_REGISTRY_LOGIN -p $DOCKER_REGISTRY_PASSWORD $CI_REGISTRY
    - docker stack deploy -c $CI_PROJECT_DIR/.docker/docker-compose-prod.yml --with-registry-auth ${SERVICE_NAME}
  environment:
    name: pre-production
    url: https://pre-prod.idci-consulting.fr/
  when: manual
  only:
    - tags
