silex:
  image: brah0um/silex-dev-idci
  volumes:
   - .:/var/www
   - /var/log/docker/nginx/idci/:/var/log/nginx
#  links:
#   - elk:syslog_server
  ports:
   - 8078:80 # edit if you want
   - 35729:35729
  environment:
   - VIRTUAL_HOST=dev.idci.fr # edit your /etc/hosts file accordingly. This value is useful if a container jwilder/nginx-proxy is running.
  restart: always
#elk:
#  image: ovski/elk:elasticdump
#  environment:
#   - VIRTUAL_HOST=dev.logs.idci.fr
#  volumes:
#   - /var/docker/elk/idci/:/data
#  ports:
#   - 8094:80 
#  restart: always
