silex:
  image: ovski/silex-prod
  volumes:
   - .:/var/www
   - /var/log/docker/nginx/idci-website/:/var/log/nginx
  links:
   - elk:syslog_server
  ports:
   - 8078:80
  environment:
   - VIRTUAL_HOST=pre-prod.idci-consulting.fr
  restart: always
elk:
  image: ovski/elk:elasticdump
  environment:
   - VIRTUAL_HOST=pre-prod.logs.idci-consulting.fr
  volumes:
   - /var/docker/pre-prod/idci-website/elk:/data
  ports:
   - 8094:80 
  restart: always
