silex:
  image: brah0um/silex-dev:1.0
  volumes:
   - .:/var/www
   - /var/log/docker/idci/nginx/:/var/log/nginx
  ports:
   - 8078:80 # edit if you want
   - 35729:35729
  environment:
   - VIRTUAL_HOST=dev.idci.fr # edit your /etc/hosts file accordingly. This value is useful if a container jwilder/nginx-proxy is running.
  restart: always
