imports:
    - { resource: "achivements.yml" }
    - { resource: "version.yml" }

logfile: "php://stderr"

swiftmailer:
    host: 'smtp.gmail.com'
    port: 465
    username: 'no-reply@idci-consulting.fr'
    password: '#no-repl'
    encryption: 'ssl'
    auth_mode: 'login'


i18n_route_generator:
    languages:
        fr: 'French'
        en: 'English'

courses:
    - 'symfony2'
    - 'html5-css3'
    - 'wordpress'

cv_theme: 'idci'

# Nav menu
menu:
    - {label: 'home', route: 'index'}
    - {label: 'our courses', route: 'courses'}
    - {label: 'the team', route: 'team'}
    - {label: 'our achievements', route: 'activities'}
    - {label: 'our partners', route: 'partners'}
    - {label: 'blog', route: 'blog'}
    - {label: 'contact', route: 'contact'}


# Ace editor
idci_code_writer:
    files:
        -
            url: https://raw.githubusercontent.com/IDCI-Consulting/GenealogyBundle/master/Controller/ImageController.php
            language: 'php'
            theme: ambiance

        -
            url: https://raw.githubusercontent.com/IDCI-Consulting/GenealogyBundle/master/Repository/ElementRepository.php
            language: 'php'
            theme: monokai

        -
            url: https://raw.githubusercontent.com/IDCI-Consulting/ExtraFormBundle/master/Controller/ApiController.php
            language: 'php'
            theme: tomorrow_night

        -
            url: https://raw.githubusercontent.com/IDCI-Consulting/SimpleScheduleBundle/master/Entity/LocationAwareCalendarEntity.php
            language: 'php'
            theme: chaos

        -
            url: https://raw.githubusercontent.com/IDCI-Consulting/SimpleScheduleBundle/master/Entity/CalendarEntityRelation.php
            language: 'php'
            theme: twilight

        -
            url: https://raw.githubusercontent.com/IDCI-Consulting/SimpleMetadataBundle/master/Resources/views/Form/fields.html.twig
            language: 'twig'
            theme: cobalt

        -
            url: https://raw.githubusercontent.com/IDCI-Consulting/BrowserCapabilities/master/js/codebarReader.js
            language: 'javascript'
            theme: clouds_midnight

        -
            url: https://raw.githubusercontent.com/IDCI-Consulting/Run4Fun/master/src/R4F/Bundle/SiteBundle/Resources/public/css/style.css
            language: 'css'
            theme: solarized_dark

# Blog page
blog:
    fr:
        categories:
            - "Symfony2"
            - "Symfony1"
            - "Wordpress"
            - "Symposium"
            - "Tutos et astuces"
            - "Divers"
        articles:
        # file property will match the url parameter for route named article

            #Divers
            - {file: "new-year2017", image: "new-year2017.jpg", title: "Nos voeux 2017", date: "13/01/2017" , author: "Louise Millon", categories: ["Divers"]}

            #Symfony1
            - {file: "creer-un-projet-symfony-1-x-depuis-la-sandbox-sous-ubuntu", image: "symfony1-logo.jpg", title: "Créer un projet Symfony 1.x depuis la sandbox sous Ubuntu", date: "29/09/2011" , author: "Gabriel Bondaz", categories: ["Symfony1"]}

            #Symfony2
            - {file: "pager-fanta", image: "symfony2-logo.png", title: "WhiteOctoberPagerfantaBundle : Comment paginer vos listes avec Symfony2 ?", date: "04/02/2013" , author: "Pierre Ferrolliet", categories: ["Symfony2"]}
            - {file: "fos-user-bundle", image: "symfony2-logo.png", title: "FOSUserBundle: Comment gérer les utilisateurs avec Symfony2", date: "26/12/2011" , author: "Pierre Ferrolliet", categories: ["Symfony2"]}
            - {file: "idci-webpage-screenshot-bundle", image: "symfony2-logo.png", title: "IDCIWebPageScreenshotBundle", date: "11/09/2013" , author: "Baptiste Bouchereau", categories: ["Symfony2"]}
            - {file: "bundle-composer-broadcast", image: "symfony2-logo.png", title: "Créer un bundle symfony2 réutilisable et le diffuser via composer", date: "15/01/2013" , author: "Baptiste Bouchereau", categories: ["Symfony2"]}
            - {file: "type-doctrine2", image: "symfony2-logo.png", title: "Comment créer un nouveau type Doctrine2 avec Symfony2", date: "18/01/2012" , author: "Pierre Ferrolliet", categories: ["Symfony2"]}
            - {file: "behaviors-doctrine2", image: "symfony2-logo.png", title: "Installer les Behaviors Doctrine2 sous Symfony2", date: "24/08/2011" , author: "Gabriel Bondaz", categories: ["Symfony2"]}
            - {file: "phpillow-couchdb", image: "symfony2-logo.png", title: "Installer PHPillow pour couchDB sur Symfony2", date: "19/06/2011" , author: "Pierre Ferrolliet", categories: ["Symfony2"]}
            - {file: "step-bundle-introduction", image: "symfony2-logo.png", title: "Introduction à IDCIStepBundle", date: "03/03/2017", author: "Louise Millon", categories: ["Symfony2"]}
            - {file: "asset-loader-bundle", image: "symfony2-logo.png", title: "La gestion des assets avec AssetLoaderBundle", date: "13/07/2017", author: "Emilio Staropoli", categories: ["Symfony2"]}

            #Symposium
            - {file: "symposium", image: "symposium.png", title: "Symposium un outil pour réussir l’organisation de vos événements", date: "22/11/2011" , author: "Frédéric Bondaz", categories: ["Symposium"]}

            #Tutos et astuces
            - {file: "environment-php-mysql", image: "mysql-php-logo.png", title: "Mettre en place un environnement de développement pour réaliser un site avec PHP et MySQL", date: "21/11/2011" , author: "Gabriel Bondaz", categories: ["Tutos et astuces"]}
            - {file: "google-apps", image: "google-logo.png", title: "Les Google Apps pour votre domaine", date: "17/06/2011" , author: "Gabriel Bondaz", categories: ["Tutos et astuces"]}

            #Wordpress
            - {file: "i18n-wordpress", image: "wordpress-logo.png", title: "Comment internationaliser un thème WordPress", date: "17/07/2013" , author: "Baptiste Bouchereau", categories: ["Wordpress"]}
            - {file: "backoffice-wordpress", image: "wordpress-logo.png", title: "Introduction au BackOffice de WordPress", date: "08/01/2012" , author: "Gabriel Bondaz", categories: ["Wordpress"]}
            - {file: "install-wordpress", image: "wordpress-logo.png", title: "Installer WordPress", date: "25/11/2011" , author: "Gabriel Bondaz", categories: ["Wordpress"]}
            - {file: "presentation-wordpress", image: "wordpress-logo.png", title: "Présentation de WordPress", date: "14/11/2011" , author: "Gabriel Bondaz", categories: ["Wordpress"]}
    en:
        categories:
            - "Symfony2"
            - "Symposium"
            - "Tutos and tips"
            - "Various"
        articles:
        # file property will match the url parameter for route named article

            #Various
            - {file: "new-year2017", image: "new-year2017.jpg", title: "Our wishes for 2017", date: "13/01/2017" , author: "Louise Millon", categories: ["Various"]}

            #Symfony2
            - {file: "idci-webpage-screenshot-bundle", image: "symfony2-logo.png", title: "IDCIWebPageScreenshotBundle", date: "11/09/2013" , author: "Baptiste Bouchereau", categories: ["Symfony2"]}
            - {file: "bundle-composer-broadcast", image: "symfony2-logo.png", title: "Create a Symfony2 Bundle reusable and broadcast it via Composer", date: "15/01/2013" , author: "Baptiste Bouchereau", categories: ["Symfony2"]}
            - {file: "type-doctrine2", image: "symfony2-logo.png", title: "How to create a new type Doctrine2 with Symfony2", date: "18/01/2012" , author: "Pierre Ferrolliet", categories: ["Symfony2"]}

            #Symposium
            - {file: "symposium", image: "symposium.png", title: "Symposium un outil pour réussir l’organisation de vos événements", date: "22/11/2011" , author: "Frédéric Bondaz", categories: ["Symposium"]}

            #Tutos and tips
            - {file: "environment-php-mysql", image: "mysql-php-logo.png", title: "Implement a workspace of developpment to realize a website with PHP and MySQL", date: "21/11/2011" , author: "Gabriel Bondaz", categories: ["Tutos and tips"]}


# Params for sitemap
sitemap:
    default:
        priority: 0.5
        lastmod: 03/03/2017
        changefreq: "monthly"
    routes:
        index:
            priority: 1
            lastmod: 03/03/2017
            changefreq: "monthly"
        courses:
            priority: 1
            lastmod: 03/03/2017
            changefreq: "monthly"
        contact:
            priority: 0.9
            lastmod: 03/03/2017
            changefreq: "monthly"
        team:
            priority: 0.7
            lastmod: 03/03/2017
            changefreq: "monthly"
        activities:
            priority: 0.7
            lastmod: 03/03/2017
            changefreq: "monthly"
        partners:
            priority: 0.6
            lastmod: 03/03/2017
            changefreq: "monthly"
        blog:
            priority: 0.9
            lastmod: 03/03/2017
            changefreq: "monthly"
        cv:
            priority: 0.8
            lastmod: 03/03/2017
            changefreq: "monthly"
            params:
                - {theme: "idci", name: "baptiste_bouchereau"}
                - {theme: "idci", name: "brahim_boukoufallah"}
                - {theme: "idci", name: "gabriel_bondaz"}
        article:
            priority: 0.8
            lastmod: 03/03/2017
            changefreq: "monthly"
            params:
                - {file: "backoffice-wordpress"}
                - {file: "behaviors-doctrine2"}
                - {file: "bundle-composer-broadcast"}
                - {file: "creer-un-projet-symfony-1-x-depuis-la-sandbox-sous-ubuntu"}
                - {file: "environment-php-mysql"}
                - {file: "fos-user-bundle"}
                - {file: "google-apps"}
                - {file: "i18n-wordpress"}
                - {file: "idci-webpage-screenshot-bundle"}
                - {file: "install-wordpress"}
                - {file: "pager-fanta"}
                - {file: "phpillow-couchdb"}
                - {file: "presentation-wordpress"}
                - {file: "symposium"}
                - {file: "type-doctrine2"}
                - {file: "new-year2017"}
