version: '3.8'

services:

  php:
    image: docker-registry.idci-consulting.fr/idci-website/php-fpm:latest
    configs:
      - source: php_conf
        target: /usr/local/etc/php/php.ini
      - source: app_env
        target: .env.local
    volumes:
      - assets_data:/var/www/app/public/build
    networks:
      - app
      - redis
      - wkhtmltopdf

  nginx:
    image: nginx
    deploy:
      labels:
        traefik.frontend.rule: "Host: preprod.idci-consulting.fr"
        traefik.docker.network: "traefik_reverse-proxy"
        traefik.port: "80"
    configs:
      - source: nginx_conf
        target: /etc/nginx/conf.d/default.conf
    volumes:
      - assets_data:/var/www/app/public/build
    environment:
      - NGINX_HOST=preprod.idci-consulting.fr
    networks:
      - traefik_reverse-proxy
      - app

  redis:
    image: redis:6
    volumes:
      - redis_data:/data
    networks:
      - redis

  wkhtmltopdf:
    image: traumfewo/docker-wkhtmltopdf-aas:latest
    environment:
      - USER=wkuser
      - PASS=Aej8biem4joh
      - PAYLOAD_LIMIT=1mb
    networks:
      wkhtmltopdf: ~

configs:
  nginx_conf:
    file: ./conf/nginx/site.conf
  php_conf:
    file: ./conf/php/php.ini
  app_env:
    file: ./conf/app/.env.prod-preprod

volumes:
  assets_data:
  redis_data:

networks:
  app:
  redis:
  wkhtmltopdf:
  traefik_reverse-proxy:
    external: true