---
version: '3.3'

services:

  traefik:
    image: traefik:latest
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
    command: --api --docker --docker.swarmMode --docker.watch
    ports:
      - "80:80"     # The HTTP port
      - "443:443"   # The HTTPS port
      - "8080:8080" # The Web UI (enabled by --api)
    configs:
      - source: traefik_config
        target: /etc/traefik/traefik.toml
    networks:
      reverse-proxy: ~

configs:
  traefik_config:
    file: ./config/traefik.toml

networks:
  reverse-proxy:
    attachable: true
    driver: overlay

