---
version: '3.9'

services:

  php:
    image: gitlab-registry.idci-consulting.fr/idci-consulting/website/php-fpm:latest
    environment:
      - APP_ENV=prod
      - APP_SECRET=ieX0ieN0chabir3shohShieda7coor7x
      - ALLOW_ROBOTS=true
      - MAILER_DSN=smtp://no-reply@idci-consulting.fr:f90ec1876c13de06cd5a4e378a62d932@mail.idci-consulting.fr:465
      - MAILER_SENDER_ADDRESS=no-reply@idci-consulting.fr
      - MAILER_RECIPIENT_ADDRESSES=["contact@idci-consulting.fr"]
      - WKHTMLTOPDF_LOGIN=wkuser
      - WKHTMLTOPDF_PASSWORD=ethi4ZooVee2
    configs:
      - source: php_conf
        target: /usr/local/etc/php/php.ini
    volumes:
      - assets_data:/var/www/app/public/build
    networks:
      - app
      - redis
      - wkhtmltopdf

  nginx:
    image: nginx
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.lbswarm=true"
        - "traefik.docker.network=traefik"

        # traefik v2
        - "traefik.http.services.idci-website-prod.loadbalancer.server.port=80"
        # HTTP Routers
        - "traefik.http.routers.to-idci-website-prod-nginx.entryPoints=web"
        - "traefik.http.routers.to-idci-website-prod-nginx.rule=Host(`www.idci-consulting.fr`)"
        - "traefik.http.routers.to-idci-website-prod-nginx.middlewares=idci-website-prod-nginx-http-to-https@docker"
        # HTTP Middlewares: http => https
        - "traefik.http.middlewares.idci-website-prod-nginx-http-to-https.redirectscheme.scheme=https"
        - "traefik.http.middlewares.idci-website-prod-nginx-http-to-https.redirectscheme.permanent=true"
        # HTTPS Routers
        - "traefik.http.routers.to-idci-website-prod-nginx-https.entryPoints=websecured"
        - "traefik.http.routers.to-idci-website-prod-nginx-https.rule=Host(`www.idci-consulting.fr`)"
        - "traefik.http.routers.to-idci-website-prod-nginx-https.tls=true"
        - "traefik.http.routers.to-idci-website-prod-nginx-https.tls.certresolver=letsencrypt"
    configs:
      - source: nginx_conf
        target: /etc/nginx/conf.d/default.conf
    volumes:
      - assets_data:/var/www/app/public/build
    environment:
      - NGINX_HOST=www.idci-consulting.fr
    networks:
      - app
      - traefik

  redis:
    image: redis:6
    volumes:
      - redis_data:/data
    networks:
      - redis

  wkhtmltopdf:
    image: traumfewo/docker-wkhtmltopdf-aas:latest
    environment:
      - USER=wkuser
      - PASS=ethi4ZooVee2
      - PAYLOAD_LIMIT=1mb
    networks:
      wkhtmltopdf: ~

configs:
  nginx_conf:
    file: ./conf/nginx/site.conf
  php_conf:
    file: ./conf/php/php.ini

volumes:
  assets_data:
  redis_data:

networks:
  app:
  redis:
  wkhtmltopdf:
  traefik:
    external: true