version: '3.8'

services:

  php:
    image: docker-registry.idci-consulting.fr/idci-website/php-fpm:dev
    configs:
      - source: php_conf
        target: /usr/local/etc/php/php.ini
    volumes:
      - ../:/var/www/app
      - composer_data:/var/www/.composer
    networks:
      - app
      - redis
      - mailhog

  nginx:
    image: nginx
    deploy:
      labels:
        - "traefik.http.routers.idci-nginx.rule=Host(`idci-website.docker`)"
        - "traefik.http.routers.idci-nginx-https.rule=Host(`idci-website.docker`)"
        - "traefik.docker.network=traefik_reverse_proxy"
        - "traefik.http.services.idci-nginx.loadbalancer.server.port=80"
        - "traefik.enable=true"
        - "traefik.docker.lbswarm=true"
        - "traefik.http.routers.idci-nginx.entryPoints=web"
        - "traefik.http.routers.idci-nginx-https.entryPoints=websecure"
        - "traefik.http.routers.idci-nginx-https.tls=true"
        - "traefik.http.routers.idci-nginx-https.tls.certresolver=letsencrypt"
    configs:
      - source: nginx_conf
        target: /etc/nginx/conf.d/default.conf
    volumes:
      - ../:/var/www/app
    environment:
      - NGINX_HOST=idci-website.docker
    networks:
      - traefik_reverse_proxy
      - app

  redis:
    image: redis:6
    volumes:
      - redis_data:/data
    networks:
      - redis

  redis-commander:
    image: rediscommander/redis-commander
    deploy:
      labels:
        - "traefik.http.routers.idci-redis-commander.rule=Host(`redis-commander.idci-website.docker`)"
        - "traefik.http.routers.idci-redis-commander-https.rule=Host(`redis-commander.idci-website.docker`)"
        - "traefik.docker.network=traefik_reverse_proxy"
        - "traefik.http.services.idci-redis-commander.loadbalancer.server.port=8081"
        - "traefik.enable=true"
        - "traefik.docker.lbswarm=true"
        - "traefik.http.routers.idci-redis-commander.entryPoints=web"
        - "traefik.http.routers.idci-redis-commander-https.entryPoints=websecure"
        - "traefik.http.routers.idci-redis-commander-https.tls=true"
        - "traefik.http.routers.idci-redis-commander-https.tls.certresolver=letsencrypt"
    environment:
      - REDIS_HOSTS=session:redis
    networks:
      - traefik_reverse_proxy
      - redis
      
  mailhog:
    image: mailhog/mailhog
    deploy:
      labels:
        - "traefik.http.routers.idci-mailhog.rule=Host(`mailhog.idci-website.docker`)"
        - "traefik.http.routers.idci-mailhog-https.rule=Host(`mailhog.idci-website.docker`)"
        - "traefik.docker.network=traefik_reverse_proxy"
        - "traefik.http.services.idci-mailhog.loadbalancer.server.port=8025"
        - "traefik.enable=true"
        - "traefik.docker.lbswarm=true"
        - "traefik.http.routers.idci-mailhog.entryPoints=web"
        - "traefik.http.routers.idci-mailhog-https.entryPoints=websecure"
        - "traefik.http.routers.idci-mailhog-https.tls=true"
        - "traefik.http.routers.idci-mailhog-https.tls.certresolver=letsencrypt"
    networks:
      - traefik_reverse_proxy
      - mailhog

configs:
  nginx_conf:
    file: ./conf/nginx/site.conf
  php_conf:
    file: ./conf/php/php.ini

volumes:
  composer_data:
  redis_data:

networks:
  app:
  redis:
  mailhog:
  traefik_reverse_proxy:
    external: true